import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by wasm-pack (npm run wasm).
    "src/wasm/**",
    // End-to-end test build and reports (npm run e2e).
    "e2e-build/**",
    "e2e-report/**",
    "e2e-results/**",
  ]),
]);

export default eslintConfig;
